### PR TITLE
Do not remove empty <a> tags that could be used as anchors.

### PR DESCRIPTION
**Pull request by rafaelbco**
Added a test. All tests are passing.

Example of empty <a> that should not be removed:

```
<a href="anchor">Link to other section</a>
Some text.
<a name="anchor" />
<h2>Other section</h2>
Some other text.
```

### CODE REVIEW

**Comment by pysailor** [comment]
Seems like a good addition to me. @wichert, would you merge this please?

**Comment by wichert** [comment]
What happens for something like `<a href="somewhere" name="anchor">..</a>`? If I read the patch right that would not be cleaned up. There should at least be a tests for links that have both `href` and `id` or `name`, as well as a test for a non-empty link with just `name`.

**Comment by rafaelbco** [comment]
> What happens for something like <a href="somewhere" name="anchor">..</a>?
The tag is non-empty, so it's not removed. It's the correct behavior, isn't it?

> There should at least be a tests for links that have both href and id or name, as well as a test for a non-empty link with just name.
I agree.

**Comment by wichert** [comment]
Thanks. Can you fix the conflicts for your branch so I can merge it?

**Comment by rafaelbco** [comment]
Done!

**Pull request merged**
